apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsschool-app-marina
  annotations:
    kubernetes.io/change-cause: "First release kuard-amd64:1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opsschool-app-marina
  template:
    metadata:
      labels:
        app: opsschool-app-marina
    spec:
      containers:
      - name: opsschool-app-marina
        image: marinapre/kandula:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
            name: http
            protocol: TCP
        env:
          - name: AWS_DEFAULT_REGION
            value: us-west-2    
        envFrom:
          - secretRef:
              name: aws-credentials  
---
apiVersion: v1
kind: Service
metadata:
  name: kandula-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: opsschool-app-marina
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5000
    