apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsschool-app-marina
  annotations:
    kubernetes.io/change-cause: "First release kuard-amd64:1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opsschool-app-marina
  template:
    metadata:
      labels:
        app: opsschool-app-marina
    spec:
      containers:
      - name: opsschool-app-marina
        image: marinapre/kandula:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
            name: http
            protocol: TCP
        env:
          - name: AWS_DEFAULT_REGION
            value: us-west-2    
        envFrom:
          - secretRef:
              name: aws-credentials  
---
apiVersion: v1
kind: Service
metadata:
  name: kandula-service-loadbalancer
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "4a0f6bb5-2409-42e6-a713-82cb75f1f081"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "kandula.ops.prezhevalsky.com"
    service.beta.kubernetes.io/do-loadbalancer-http2-ports: 443,80
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-2:264772297631:certificate/a6d23e9f-b4f5-4dcc-9f0d-a18972b943ef"
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  #   service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:967481731151:certificate/4a0f6bb5-2409-42e6-a713-82cb75f1f081
  #   service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"      
spec:
  type: LoadBalancer
  selector:
    app: opsschool-app-marina
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5000
    

 