apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQTZDUVRIVkJIWUZDRlJWUjM=
  AWS_SECRET_ACCESS_KEY: bEFqUTNmTlU3dnAyUGVycXhIQlBVelZJY1lFYmtpakdPcWU4MUpEbg==
