apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQTZDUVRIVkJIV1FBTFBMTTM=
  AWS_SECRET_ACCESS_KEY: bUR3ZGtGaUZkTjZIeVYwNVVJWnROM3I3OWFjUzBRaGh1UzRzcVY5QQ==



